routes/web.php
	Route::get('issue-thread/{issueList}','IssueThreadController@show')->name('issue-thread.show');
	Route::post('issue-thread/{issueList}','IssueThreadController@store')->name('issue-thread.store');	
	
});

Route::post('/alert-status/{issueList}','SearchController@email_alert')->name('update-alert-status');
Route::post('/tickets/{issueList}/issue-thread/store','IssueListController@postTopic')->name('admin-issue-thread.store');
Route::post('/tickets/{issueList}','IssueListController@update')->name('tickets.update');
//Admin tickets 
Route::get('/tickets/show/{issueList}','AdminTicketController@show')->name('admin-tickets.show');
Route::get('/tickets/{issueList}/edit','AdminTicketController@edit')->name('admin-tickets.edit');
Route::post('/tickets/{issueList}','AdminTicketController@update')->name('admin-tickets.update');
Route::get('/tickets/delete/{issueList}','AdminTicketController@destroy')->name('admin-tickets.delete');

Route::get('issue-thread','IssueThreadController@index')->name('issue-thread.index');
Route::get('issue-thread','IssueThreadController@index')->name('issue-thread.index');
Route::post('issue-thread/reply/{issueThread}','IssueThreadController@sendReply')->name('issue-thread.sendReply');
// Route::resource('issue-thread','IssueThreadController');


Route::prefix('ae')->group(function () {

	/*************************
	* Ae Account             *
	*************************/
	Route::get('/login', 'Auth\AccountExecutiveLoginController@showLoginform')->name('ae-login');
	Route::post('/login', 'Auth\AccountExecutiveLoginController@login')->name('ae-login');
	
	Route::get('/my-account/card', 'AeProjectController@index_card')->name('ae-card-project');
	Route::post('/my-account/card','AeProjectController@index_card')->name('ae-card-project');	

	Route::get('/my-account/projects/show/{project}', 'AeProjectController@show')->name('ae-show-project');
	Route::get('/my-account/projects/download/{project}', 'AeProjectController@download')->name('ae-download-project');
	Route::post('/my-account/projects/uploads/{project}', 'AeProjectController@upload')->name('ae-upload-project-files');
	Route::get('/my-account','AeProjectController@index')->name('my-account.index');
	Route::post('/my-account','AeProjectController@index')->name('my-account.index');
	

	Route::get('/my-account/change-pass/{user}', 'AeController@changePassword')->name('ae-accounts-change-pass');
	Route::post('/my-account/change-pass/{user}', 'AeController@updatePassword')->name('ae-accounts-change-pass');

	Route::get('/my-account/ticket/{issueList}','AeTicketController@show')->name('ae-ticket-show');
	Route::post('/my-account/ticket/forum/{issueList}','AeTicketController@postTopic')->name('ae-ticket-post-topic');
	Route::post('/my-account/ticket/reply/{issueThread}','AeTicketController@sendReply')->name('ae-ticket-post-reply');
});
	/*************************
	* AE Password Reset *
	*************************/
	Route::post('/ae/password/email', 'Auth\AeForgotPasswordController@sendResetLinkEmail')->name('ae-password-email');
	Route::get('/ae/password/reset', 'Auth\AeForgotPasswordController@showLinkRequestForm')->name('ae-password-request');
	Route::post('/ae/password/reset', 'Auth\AeResetPasswordController@reset');
	Route::get('/ae/password/reset/{token}', 'Auth\AeResetPasswordController@showResetForm')->name('ae-password-reset');


/*************************
* Designation         	 *
*************************/
Route::post('designations/{designation}', 'DesignationController@update');
Route::get('designations/delete/{designation}', 'DesignationController@destroy');
Route::resource('designations', 'DesignationController');


/*************************
* Clients Logout         *
*************************/
Route::get('/client-logout', 'Auth\ClientLoginController@logout')->name('client-logout');
Route::get('/admin-logout', 'Auth\LoginController@userLogout')->name('admin-logout');
Route::get('/ae-logout', 'Auth\AccountExecutiveLoginController@userLogout')->name('ae-logout');
Route::get('/technical-logout', 'Auth\TechTeamLoginController@userLogout')->name('techTeam-logout');
Route::post('/ae-logout', 'Auth\AccountExecutiveLoginController@logout')->name('ae-logout');
Route::post('/client-logout', 'Auth\ClientLoginController@logout')->name('client-logout');
Route::post('/admin-logout', 'Auth\LoginController@userLogout')->name('admin-logout');
Route::post('/technical-logout', 'Auth\TechTeamLoginController@logout')->name('techTeam-logout');

/*************************
* Clients                *
*************************/
Route::get('/clients', 'AccountController@index')->name('client-account');
Route::get('/clients/new', 'AccountController@create')->name('new-client-account');
Route::post('/clients/new', 'AccountController@store')->name('new-client-account');
Route::get('/clients/edit/{account}', 'AccountController@edit')->name('update-client-account');
Route::post('/clients/edit/{account}', 'AccountController@update')->name('update-client-account');
Route::get('/clients/show/{account}', 'AccountController@show')->name('show-client-account');
Route::get('/clients/delete/{account}', 'AccountController@destroy')->name('delete-client-account');


/*************************
* Change Request         *
*************************/
Route::get('/change-requests','ChangeRequestController@index')->name('change-requests.index');
Route::post('/change-requests','ChangeRequestController@index')->name('change-requests.index');
Route::post('/change-requests/store','ChangeRequestController@store')->name('change-requests.store');
Route::get('/change-requests/create','ChangeRequestController@create')->name('change-requests.create');
Route::get('/change-requests/{changerequest}/edit','ChangeRequestController@edit')->name('change-requests.edit');
Route::post('/change-requests/{changerequest}','ChangeRequestController@update')->name('change-requests.update');
Route::get('/change-requests/{changerequest}','ChangeRequestController@show')->name('change-requests.show');
Route::get('/change-requests/delete/{changerequest}','ChangeRequestController@destroy')->name('change-requests.delete');

/*************************
* Projects                *
*************************/
Route::get('/projects', 'ProjectController@index')->name('client-project');
Route::get('/projects/tabular', 'ProjectController@index_tabular')->name('client-project-tabular');
Route::post('/projects/tabular', 'ProjectController@index_tabular')->name('client-project-tabular');

Route::get('/projects/mandays-to-date', 'ProjectController@timelineDate')->name('mandays-to-date');

Route::get('/projects/new', 'ProjectController@create')->name('new-project');
Route::post('/projects/new', 'ProjectController@store')->name('new-project');

Route::get('/projects/new/{account}', 'ProjectController@create')->name('new-project-account');
Route::post('/projects/new/{account}', 'ProjectController@store')->name('new-project-account');

Route::get('/projects/edit/{project}', 'ProjectController@edit')->name('update-project');
Route::post('/projects/edit/{project}', 'ProjectController@update')->name('update-project');
Route::get('/projects/show/{project}', 'ProjectController@show')->name('show-project');
Route::get('/projects/delete/{project}', 'ProjectController@destroy')->name('delete-project');

Route::post('/projects/uploads/{project}', 'ProjectController@upload')->name('upload-project-files');
Route::get('/projects/download/{projectid}/{filefolder}/{filename}', function($projectid, $filefolder, $filename) {
	return response()->download(storage_path('app/file_projects/'.$projectid.'/'.$filefolder.'/'.$filename));
})->name('download-project-files');

Route::get('/projects/download/{projectid}', function($projectid) {

	// shell_exec( $cmd,$output);
	$zipName = 'files.zip';
	$rootPath = storage_path('app/file_projects/'.$projectid);

	if (file_exists(storage_path('app/file_projects/'.$projectid.'/'.$zipName))) {
		unlink(storage_path('app/file_projects/'.$projectid.'/'.$zipName));
	}

	$zip = new ZipArchive();
	$zip->open($rootPath.'/'.$zipName, ZipArchive::CREATE | ZipArchive::OVERWRITE);

	// Create recursive directory iterator
	/** @var SplFileInfo[] $files */
	$files = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator($rootPath),
		RecursiveIteratorIterator::LEAVES_ONLY
	);
	$cnt= 0;
	foreach ($files as $name => $file)
	{
		// Skip directories (they would be added automatically)
		if (!$file->isDir())
		{
			// Get real and relative path for current file
			$filePath = $file->getRealPath();
			$relativePath = substr($filePath, strlen($rootPath) + 1);
			if ( $cnt == 10 ) {
				$cnt = 0;
				set_time_limit ( 30 ); //if it doesnt work try to use ini_set('max_execution_time', 30);
			}
			// Add current file to archive
			$zip->addFile($filePath, $relativePath);
		}
		$cnt++;
	}

	// Zip archive will be created only after closing object
	$zip->close();

	return response()->download(storage_path('app/file_projects/'.$projectid.'/'.$zipName));
})->name('download-project-files-all');

Route::get('/projects/category/download/{projectid}/{categoryid}', function($projectid, $categoryid) {

	$zipName = 'filesCategory'.$categoryid.'.zip';
	$rootPath = storage_path('app/file_projects/'.$projectid.'/'.$categoryid);

	if (file_exists(storage_path('app/file_projects/'.$projectid.'/'.$categoryid.'/'.$zipName))) {
		unlink(storage_path('app/file_projects/'.$projectid.'/'.$categoryid.'/'.$zipName));
	}

	$zip = new ZipArchive();
	$zip->open($rootPath.'/'.$zipName, ZipArchive::CREATE | ZipArchive::OVERWRITE);

	// Create recursive directory iterator
	/** @var SplFileInfo[] $files */
	$files = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator($rootPath),
		RecursiveIteratorIterator::LEAVES_ONLY
	);

	foreach ($files as $name => $file)
	{
		// Skip directories (they would be added automatically)
		if (!$file->isDir())
		{
			// Get real and relative path for current file
			$filePath = $file->getRealPath();

app/Designation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Designation extends Model
{
        use SoftDeletes;
        protected $fillable = [ 'designation'];


//  function project()
//     {
//         return $this->belongsTo('App\Project')->withDefault();
//     }

function user()
    {
        return $this->belongsTo('App\User','id','designation');
    }

}

app/Http/Controllers/DesignationController.php
<?php

namespace App\Http\Controllers;

use App\Designation;
use Illuminate\Http\Request;

class DesignationController extends Controller
{

   
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     * 
     */
    public function index()
    {
        $designationsQeury = Designation::orderBy('created_at');
        $designations = $designationsQeury->paginate(config('constants.pagination'));

        return view('admin.designation.view',compact('designations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $designation = new Designation;
        $pageName = 'New Designation';
        $route = route('designations.store');
        return view('admin.designation.form',compact('designation','pageName','route'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'designation' => 'required|min:3|unique:designations'
        ]);

        $designation = Designation::create(['designation'=>$request->designation]);

        return redirect()->route('designations.index');


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Designation  $designation
     * @return \Illuminate\Http\Response
     */
    public function show(Designation $designation)
    {
        dd($designation->user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Designation  $designation
     * @return \Illuminate\Http\Response
     */
    public function edit(Designation $designation)
    {
        $pageName = 'Edit Designation';
        $route = route('designations.update',$designation->id);
        return view('admin.designation.form',compact('pageName','route','designation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Designation  $designation
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Designation $designation)
    {
        
         $this->validate($request,[
            'designation' => 'required|min:3|unique:designations,designation,'.$designation->id
        ]);

        $designation->designation = $request->designation;
        $designation->save();

        return redirect()->route('designations.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Designation  $designation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Designation $designation)
    {
        if(!empty($designation->user))
        {
        
        }else{
            $designation->delete();
            return 1;
        }
      
    }
}

resources/views/admin/designation/form.blade.php
@extends('layouts.adminlayout')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">Designations</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ $pageName }}
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <form class="form-horizontal" method="POST" action="{{ $route }}">
                                {{ csrf_field() }}

                                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                    <label for="designation" class="col-md-2 control-label"><span class="asterisk-marker">*</span> Designation</label>

                                    <div class="col-md-10">
                                        <input id="designation" type="text" class="form-control" name="designation" value="{{ !empty(old('designation'))?old('designation'):$designation->designation }}" required autofocus>

                                        @if ($errors->has('designation'))
                                               <span class="error-block">
                                                <strong>{{ $errors->first('designation') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>          
                                <div class="form-group">
                                    <div class="col-md-10 col-md-offset-2">
                                        <button type="submit" class="btn btn-primary">
                                            Save
                                        </button>
                                        <a href="{{ route('designations.index') }}">
                                            <button type="button" class="btn btn-default">
                                                Cancel
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
@endsection

resources/views/admin/designation/view.blade.php
@extends('layouts.adminlayout')

@section('content')
<div class="row">
                    <div class="col-lg-12">
                        <h3 class="page-header">Designations</h3>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
                <div class="row">
                    <div class="col-lg-12">
                            <p class="text-right">
                                <a href="{{ route('designations.create') }}"><button type="button" class="btn btn-success btn-rectangle"><i class="fa fa-plus"> New</i></button></a>
                            </p>
                            <div class="dataTable_wrapper">
                                <?php 
                                    $ctr = 1;
                                ?>
                                <div class="row">
                                    @if(count($designations) > 0)
                                        @foreach ($designations as $designation)
                                            <div class="col-lg-4 col-md-6">
                                                <div class="panel panel-primary">
                                                    <a href="{{ route('service-types.show', $designation->id) }}">
                                                        <div class="panel-heading">
                                                            <div class="row">
                                                                <div class="col-xs-12">
                                                                    <div><strong>{{ $designation->designation }}</strong></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </a>
                                                    <div class="panel-footer">
                                                        <small>
                                                            <a href="{{ route('designations.edit', $designation->id) }}">
                                                                <span class="pull-left"><i class="fa fa-arrow-circle-right"></i></span>
                                                                <span class="pull-left">&nbsp;Edit Details</span>
                                                            </a>
                                                            <a class="pull-right ">
                                                                <span class="pull-right imanila-color" style="cursor:pointer;"><i class="fa fa-close" onclick="javascript:deletedesignation({{ $designation->id }})"></i></span>
                                                            </a>
                                                        </small>
                                                        <div class="clearfix"></div>
                                                    </div>
                                                </div>
                                            </div>
                                            @if($ctr % 3 == 0)
                                                </div>
                                                <div class="row">
                                            @endif
                                            <?php $ctr++; ?>
                                        @endforeach
                                    @else
                                                    <h2>Empty Designation List</h2>
                                    @endif
                                <div class="col-lg-12 text-center">
                                    {{ $designations->links() }}
                                </div>
                            </div>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>

<script>
    
function deletedesignation(designationId) {
	if (confirm('Are you sure you want to delete this designation?')) {
		$.ajax({
			type:'GET',
			url:'/designations/delete/'+designationId,
			success:function(data){
                alert(data)
				window.location = '/designations';
			}
		});
	}
}
</script>

@endsection